# Generated by Django 5.0.3 on 2024-03-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_order_date_order_alter_order_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='about',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
