# Generated by Django 5.0.3 on 2024-04-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_customeraddress_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
