# Generated by Django 5.0.3 on 2024-04-29 10:41

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_alter_customeraddress_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
