# Generated by Django 5.0.4 on 2024-04-29 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('kg', 'Kg level'), ('Elementary', 'Elementary level'), ('HighSchool', 'HighSchool level'), ('Undergraduate', 'Undergraduate level'), ('Msc', 'Msc level'), ('Phd', 'Phd level')], max_length=100),
        ),
    ]
